# Generated by Django 2.1.3 on 2018-11-15 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('rus_name', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name_plural': 'cities',
            },
        ),
    ]
